package com.genlot.lottery.dao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.genlot.lottery.dao.entity.Notice;
import com.genlot.lottery.dao.entity.User;

import com.genlot.lottery.dao.greendao.NoticeDao;
import com.genlot.lottery.dao.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noticeDaoConfig;
    private final DaoConfig userDaoConfig;

    private final NoticeDao noticeDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noticeDaoConfig = daoConfigMap.get(NoticeDao.class).clone();
        noticeDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        noticeDao = new NoticeDao(noticeDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Notice.class, noticeDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        noticeDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public NoticeDao getNoticeDao() {
        return noticeDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
